/Users/tshi/.pyenv/versions/3.10.4/bin/python3.10 /Users/tshi/PycharmProjects/breachin/breachin/project_diff/exe.py
added module 23
[('django/core/management/commands', '__init__.py'), ('django/contrib/auth/management/commands', '__init__.py'), ('django/contrib/staticfiles/management', '__init__.py'), ('django/contrib/staticfiles/management/commands', '__init__.py'), ('django/contrib/sessions/management', '__init__.py'), ('django/contrib/sessions/management/commands', '__init__.py'), ('django/contrib/sitemaps/management', '__init__.py'), ('django/contrib/sitemaps/management/commands', '__init__.py'), ('django/contrib/contenttypes/management/commands', '__init__.py'), ('django/contrib/gis/management', '__init__.py'), ('django/contrib/gis/management/commands', '__init__.py'), ('django/conf/locale/uz', '__init__.py'), ('django/conf/locale/uz', 'formats.py'), ('django/conf/locale/ar_DZ', '__init__.py'), ('django/conf/locale/ar_DZ', 'formats.py'), ('django/conf/locale/ky', '__init__.py'), ('django/conf/locale/ky', 'formats.py'), ('django/conf/locale/ig', '__init__.py'), ('django/conf/locale/ig', 'formats.py'), ('django/conf/locale/tk', '__init__.py'), ('django/conf/locale/tk', 'formats.py'), ('django/conf/locale/tg', '__init__.py'), ('django/conf/locale/tg', 'formats.py')]
removed module 11
[('django/utils', 'lru_cache.py'), ('django/contrib/staticfiles/templatetags', '__init__.py'), ('django/db/backends/postgresql_psycopg2', 'creation.py'), ('django/db/backends/postgresql_psycopg2', 'client.py'), ('django/db/backends/postgresql_psycopg2', '__init__.py'), ('django/db/backends/postgresql_psycopg2', 'features.py'), ('django/db/backends/postgresql_psycopg2', 'operations.py'), ('django/db/backends/postgresql_psycopg2', 'utils.py'), ('django/db/backends/postgresql_psycopg2', 'introspection.py'), ('django/db/backends/postgresql_psycopg2', 'base.py'), ('django/db/backends/postgresql_psycopg2', 'schema.py')]
moved module 1
['__init__.py']

Process finished with exit code 0

